- name: "Configure LibreOffice for Arch Linux"
  ansible.builtin.include_tasks: archlinux/main.yml
  when: ansible_os_family == "Archlinux"

- name: "Configure LibreOffice for FreeBSD"
  ansible.builtin.include_tasks: freebsd/main.yml
  when: ansible_os_family == "FreeBSD"

